/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BedanktRouteImport } from './routes/bedankt'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DienstenRouteImport } from './routes/diensten'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as OverOnsRouteImport } from './routes/over-ons'
import { Route as SeoSpecialistEnschedeRouteImport } from './routes/seo-specialist-enschede'
import { Route as SeoTwenteRouteImport } from './routes/seo-twente'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WebdesignEnschedeRouteImport } from './routes/webdesign-enschede'
import { Route as WebdesignHengeloRouteImport } from './routes/webdesign-hengelo'
import { Route as WebshopLatenMakenAlmeloRouteImport } from './routes/webshop-laten-maken-almelo'
import { Route as WebsiteLatenMakenTwenteRouteImport } from './routes/website-laten-maken-twente'
import { Route as WebsiteScanRouteImport } from './routes/website-scan'
import { Route as WerkRouteImport } from './routes/werk'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BedanktRoute = BedanktRouteImport.update({
  id: '/bedankt',
  path: '/bedankt',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DienstenRoute = DienstenRouteImport.update({
  id: '/diensten',
  path: '/diensten',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const OverOnsRoute = OverOnsRouteImport.update({
  id: '/over-ons',
  path: '/over-ons',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoSpecialistEnschedeRoute = SeoSpecialistEnschedeRouteImport.update({
  id: '/seo-specialist-enschede',
  path: '/seo-specialist-enschede',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoTwenteRoute = SeoTwenteRouteImport.update({
  id: '/seo-twente',
  path: '/seo-twente',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WebdesignEnschedeRoute = WebdesignEnschedeRouteImport.update({
  id: '/webdesign-enschede',
  path: '/webdesign-enschede',
  getParentRoute: () => rootRouteImport,
} as any)
const WebdesignHengeloRoute = WebdesignHengeloRouteImport.update({
  id: '/webdesign-hengelo',
  path: '/webdesign-hengelo',
  getParentRoute: () => rootRouteImport,
} as any)
const WebshopLatenMakenAlmeloRoute = WebshopLatenMakenAlmeloRouteImport.update({
  id: '/webshop-laten-maken-almelo',
  path: '/webshop-laten-maken-almelo',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteLatenMakenTwenteRoute = WebsiteLatenMakenTwenteRouteImport.update({
  id: '/website-laten-maken-twente',
  path: '/website-laten-maken-twente',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteScanRoute = WebsiteScanRouteImport.update({
  id: '/website-scan',
  path: '/website-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const WerkRoute = WerkRouteImport.update({
  id: '/werk',
  path: '/werk',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bedankt': typeof BedanktRoute
  '/contact': typeof ContactRoute
  '/diensten': typeof DienstenRoute
  '/mcp': typeof McpRoute
  '/over-ons': typeof OverOnsRoute
  '/seo-specialist-enschede': typeof SeoSpecialistEnschedeRoute
  '/seo-twente': typeof SeoTwenteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/webdesign-enschede': typeof WebdesignEnschedeRoute
  '/webdesign-hengelo': typeof WebdesignHengeloRoute
  '/webshop-laten-maken-almelo': typeof WebshopLatenMakenAlmeloRoute
  '/website-laten-maken-twente': typeof WebsiteLatenMakenTwenteRoute
  '/website-scan': typeof WebsiteScanRoute
  '/werk': typeof WerkRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bedankt': typeof BedanktRoute
  '/contact': typeof ContactRoute
  '/diensten': typeof DienstenRoute
  '/mcp': typeof McpRoute
  '/over-ons': typeof OverOnsRoute
  '/seo-specialist-enschede': typeof SeoSpecialistEnschedeRoute
  '/seo-twente': typeof SeoTwenteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/webdesign-enschede': typeof WebdesignEnschedeRoute
  '/webdesign-hengelo': typeof WebdesignHengeloRoute
  '/webshop-laten-maken-almelo': typeof WebshopLatenMakenAlmeloRoute
  '/website-laten-maken-twente': typeof WebsiteLatenMakenTwenteRoute
  '/website-scan': typeof WebsiteScanRoute
  '/werk': typeof WerkRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bedankt': typeof BedanktRoute
  '/contact': typeof ContactRoute
  '/diensten': typeof DienstenRoute
  '/mcp': typeof McpRoute
  '/over-ons': typeof OverOnsRoute
  '/seo-specialist-enschede': typeof SeoSpecialistEnschedeRoute
  '/seo-twente': typeof SeoTwenteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/webdesign-enschede': typeof WebdesignEnschedeRoute
  '/webdesign-hengelo': typeof WebdesignHengeloRoute
  '/webshop-laten-maken-almelo': typeof WebshopLatenMakenAlmeloRoute
  '/website-laten-maken-twente': typeof WebsiteLatenMakenTwenteRoute
  '/website-scan': typeof WebsiteScanRoute
  '/werk': typeof WerkRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bedankt'
    | '/contact'
    | '/diensten'
    | '/mcp'
    | '/over-ons'
    | '/seo-specialist-enschede'
    | '/seo-twente'
    | '/sitemap.xml'
    | '/webdesign-enschede'
    | '/webdesign-hengelo'
    | '/webshop-laten-maken-almelo'
    | '/website-laten-maken-twente'
    | '/website-scan'
    | '/werk'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bedankt'
    | '/contact'
    | '/diensten'
    | '/mcp'
    | '/over-ons'
    | '/seo-specialist-enschede'
    | '/seo-twente'
    | '/sitemap.xml'
    | '/webdesign-enschede'
    | '/webdesign-hengelo'
    | '/webshop-laten-maken-almelo'
    | '/website-laten-maken-twente'
    | '/website-scan'
    | '/werk'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bedankt'
    | '/contact'
    | '/diensten'
    | '/mcp'
    | '/over-ons'
    | '/seo-specialist-enschede'
    | '/seo-twente'
    | '/sitemap.xml'
    | '/webdesign-enschede'
    | '/webdesign-hengelo'
    | '/webshop-laten-maken-almelo'
    | '/website-laten-maken-twente'
    | '/website-scan'
    | '/werk'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/.mcp/invoke-tool/$tool'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BedanktRoute: typeof BedanktRoute
  ContactRoute: typeof ContactRoute
  DienstenRoute: typeof DienstenRoute
  McpRoute: typeof McpRoute
  OverOnsRoute: typeof OverOnsRoute
  SeoSpecialistEnschedeRoute: typeof SeoSpecialistEnschedeRoute
  SeoTwenteRoute: typeof SeoTwenteRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WebdesignEnschedeRoute: typeof WebdesignEnschedeRoute
  WebdesignHengeloRoute: typeof WebdesignHengeloRoute
  WebshopLatenMakenAlmeloRoute: typeof WebshopLatenMakenAlmeloRoute
  WebsiteLatenMakenTwenteRoute: typeof WebsiteLatenMakenTwenteRoute
  WebsiteScanRoute: typeof WebsiteScanRoute
  WerkRoute: typeof WerkRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bedankt': {
      id: '/bedankt'
      path: '/bedankt'
      fullPath: '/bedankt'
      preLoaderRoute: typeof BedanktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diensten': {
      id: '/diensten'
      path: '/diensten'
      fullPath: '/diensten'
      preLoaderRoute: typeof DienstenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-ons': {
      id: '/over-ons'
      path: '/over-ons'
      fullPath: '/over-ons'
      preLoaderRoute: typeof OverOnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-specialist-enschede': {
      id: '/seo-specialist-enschede'
      path: '/seo-specialist-enschede'
      fullPath: '/seo-specialist-enschede'
      preLoaderRoute: typeof SeoSpecialistEnschedeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-twente': {
      id: '/seo-twente'
      path: '/seo-twente'
      fullPath: '/seo-twente'
      preLoaderRoute: typeof SeoTwenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webdesign-enschede': {
      id: '/webdesign-enschede'
      path: '/webdesign-enschede'
      fullPath: '/webdesign-enschede'
      preLoaderRoute: typeof WebdesignEnschedeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webdesign-hengelo': {
      id: '/webdesign-hengelo'
      path: '/webdesign-hengelo'
      fullPath: '/webdesign-hengelo'
      preLoaderRoute: typeof WebdesignHengeloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webshop-laten-maken-almelo': {
      id: '/webshop-laten-maken-almelo'
      path: '/webshop-laten-maken-almelo'
      fullPath: '/webshop-laten-maken-almelo'
      preLoaderRoute: typeof WebshopLatenMakenAlmeloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-laten-maken-twente': {
      id: '/website-laten-maken-twente'
      path: '/website-laten-maken-twente'
      fullPath: '/website-laten-maken-twente'
      preLoaderRoute: typeof WebsiteLatenMakenTwenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-scan': {
      id: '/website-scan'
      path: '/website-scan'
      fullPath: '/website-scan'
      preLoaderRoute: typeof WebsiteScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/werk': {
      id: '/werk'
      path: '/werk'
      fullPath: '/werk'
      preLoaderRoute: typeof WerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BedanktRoute: BedanktRoute,
  ContactRoute: ContactRoute,
  DienstenRoute: DienstenRoute,
  McpRoute: McpRoute,
  OverOnsRoute: OverOnsRoute,
  SeoSpecialistEnschedeRoute: SeoSpecialistEnschedeRoute,
  SeoTwenteRoute: SeoTwenteRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WebdesignEnschedeRoute: WebdesignEnschedeRoute,
  WebdesignHengeloRoute: WebdesignHengeloRoute,
  WebshopLatenMakenAlmeloRoute: WebshopLatenMakenAlmeloRoute,
  WebsiteLatenMakenTwenteRoute: WebsiteLatenMakenTwenteRoute,
  WebsiteScanRoute: WebsiteScanRoute,
  WerkRoute: WerkRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
