/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BedanktRouteImport } from './routes/bedankt'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DienstenRouteImport } from './routes/diensten'
import { Route as OverOnsRouteImport } from './routes/over-ons'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WebsiteScanRouteImport } from './routes/website-scan'
import { Route as WerkRouteImport } from './routes/werk'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BedanktRoute = BedanktRouteImport.update({
  id: '/bedankt',
  path: '/bedankt',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DienstenRoute = DienstenRouteImport.update({
  id: '/diensten',
  path: '/diensten',
  getParentRoute: () => rootRouteImport,
} as any)
const OverOnsRoute = OverOnsRouteImport.update({
  id: '/over-ons',
  path: '/over-ons',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteScanRoute = WebsiteScanRouteImport.update({
  id: '/website-scan',
  path: '/website-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const WerkRoute = WerkRouteImport.update({
  id: '/werk',
  path: '/werk',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bedankt': typeof BedanktRoute
  '/contact': typeof ContactRoute
  '/diensten': typeof DienstenRoute
  '/over-ons': typeof OverOnsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/website-scan': typeof WebsiteScanRoute
  '/werk': typeof WerkRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bedankt': typeof BedanktRoute
  '/contact': typeof ContactRoute
  '/diensten': typeof DienstenRoute
  '/over-ons': typeof OverOnsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/website-scan': typeof WebsiteScanRoute
  '/werk': typeof WerkRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bedankt': typeof BedanktRoute
  '/contact': typeof ContactRoute
  '/diensten': typeof DienstenRoute
  '/over-ons': typeof OverOnsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/website-scan': typeof WebsiteScanRoute
  '/werk': typeof WerkRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bedankt'
    | '/contact'
    | '/diensten'
    | '/over-ons'
    | '/sitemap.xml'
    | '/website-scan'
    | '/werk'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bedankt'
    | '/contact'
    | '/diensten'
    | '/over-ons'
    | '/sitemap.xml'
    | '/website-scan'
    | '/werk'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/bedankt'
    | '/contact'
    | '/diensten'
    | '/over-ons'
    | '/sitemap.xml'
    | '/website-scan'
    | '/werk'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BedanktRoute: typeof BedanktRoute
  ContactRoute: typeof ContactRoute
  DienstenRoute: typeof DienstenRoute
  OverOnsRoute: typeof OverOnsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WebsiteScanRoute: typeof WebsiteScanRoute
  WerkRoute: typeof WerkRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bedankt': {
      id: '/bedankt'
      path: '/bedankt'
      fullPath: '/bedankt'
      preLoaderRoute: typeof BedanktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diensten': {
      id: '/diensten'
      path: '/diensten'
      fullPath: '/diensten'
      preLoaderRoute: typeof DienstenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-ons': {
      id: '/over-ons'
      path: '/over-ons'
      fullPath: '/over-ons'
      preLoaderRoute: typeof OverOnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-scan': {
      id: '/website-scan'
      path: '/website-scan'
      fullPath: '/website-scan'
      preLoaderRoute: typeof WebsiteScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/werk': {
      id: '/werk'
      path: '/werk'
      fullPath: '/werk'
      preLoaderRoute: typeof WerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BedanktRoute: BedanktRoute,
  ContactRoute: ContactRoute,
  DienstenRoute: DienstenRoute,
  OverOnsRoute: OverOnsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WebsiteScanRoute: WebsiteScanRoute,
  WerkRoute: WerkRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
